### ISSUE TITLE
Property usage in strongly-typed Hub

### ISSUE THREAD

**Issue by stratever** [aspnet/SignalR-Server#159]
Let's have a strongly-typed hub like this:

```
public class TestHub : Hub<IClient>
{
    public void DoSomething()
    {
        Clients.Caller.UserPriority = 1;
    }
}
```
And the IClient interface is the following:

```
public interface IClient
{
    int UserPriority { get; set; }
}
```
I got the following runtime error when I try to invoke DoSomething:

```
 Unhandled Exception: System.InvalidOperationException: The interface 'IClient' m
ust not contain any properties.
at Microsoft.AspNetCore.SignalR.Hubs.TypedClientBuilder`1.VerifyInterface(Typ
e interfaceType)
at Microsoft.AspNetCore.SignalR.Hubs.TypedClientBuilder`1.GenerateClientBuild
er()
at Microsoft.AspNetCore.SignalR.Hubs.TypedClientBuilder`1.<>c.<.cctor>b__12_0
()
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at System.Lazy`1.get_Value()
at Microsoft.AspNetCore.SignalR.Hubs.TypedClientBuilder`1.Build(IClientProxy
proxy)
at CallSite.Target(Closure , CallSite , Type , Object )
at Microsoft.AspNetCore.SignalR.Hubs.TypedHubCallerConnectionContext`1.get_Ca
ller()
```
But in a non-strongly-typed Hub, I can set a property to Caller (dynamic):

```
public class TestHub : Hub
{
    public void DoSomething()
    {
        Clients.Caller.UserPriority = 1;
    }
}
```
This doesn't make sense to me. Why can I not use properties in a strongly-typed Hub?

**Comment by muratg** [comment]
We're planning to cut HubState feature in SignalR Core.

See #196 for rest of 1.1 planning.
