### ISSUE TITLE
SignalR stops server shutdown

### ISSUE THREAD

**Issue by Praburaj** [aspnet/SignalR-Server#59]
This looks like a regression. If a web app has signalR wired and I try to stop the server it stops with this error (`[INFORMATION:Microsoft.AspNet.Server.WebListener.MessagePump] Stopping, waiting for 1 request(s) to drain.`). 

Repro steps:
1. Start the app by executing `k web`. 
2. Make a request to the application
3. Try to press enter from command line to terminate the app to see this log and gets stuck there for ever. 

```
d:\K\MusicStore\src\MusicStore>k web
[INFORMATION:Microsoft.Net.Http.Server.WebListener] Start
[INFORMATION:Microsoft.Net.Http.Server.WebListener] Listening on prefix: http://localhost:5002/
Started

[INFORMATION:Microsoft.AspNet.Server.WebListener.MessagePump] Stopping, waiting for 1 request(s) to drain.
```

**Comment by suhasj** [comment]
+1 with latest KRE and beta3 packages

**Comment by Tragetaschen** [comment]
The same is happening with Kestrel (see aspnet/KestrelHttpServer#60).

I've got a stack trace while being in Kestrel's Dispose-logic (so after ApplicationStopping was signaled), where the transport heartbeat still fires:

```
 at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at Microsoft.AspNet.Server.Kestrel.Networking.UvAsyncHandle.Send()
   at Microsoft.AspNet.Server.Kestrel.KestrelThread.Post(Action`1 callback, Object state)
   at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.Write(ArraySegment`1 buffer, Action`2 callback, Object state)
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.Write(ArraySegment`1 data, Action`2 callback, Object state)
   at Microsoft.AspNet.Server.Kestrel.Http.FrameResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNet.Server.Kestrel.Http.FrameResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNet.SignalR.ResponseExtensions.Write(HttpResponse response, ArraySegment`1 data)
   at Microsoft.AspNet.SignalR.Transports.ServerSentEventsTransport.PerformKeepAlive(Object state)
   at Microsoft.AspNet.SignalR.Transports.ServerSentEventsTransport.<>c__DisplayClass0.<KeepAlive>b__1(Object state)
   at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.InvokeNext(Func`2 next, Object nextState, Object queueState)
   at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.<>c__DisplayClass0.<Enqueue>b__1(Func`2 n, Object ns, TaskQueue q)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod[T1,T2,T3](Func`4 func, T1 arg1, T2 arg2, T3 arg3)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.Then[T1,T2,T3](Task task, Func`4 successor, T1 arg1, T2 arg2, T3 arg3)
   at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.Enqueue(Func`2 taskFunc, Object state)
   at Microsoft.AspNet.SignalR.Transports.TransportDisconnectBase.EnqueueOperation(Func`2 writeAsync, Object state)
   at Microsoft.AspNet.SignalR.Transports.ServerSentEventsTransport.KeepAlive()
   at Microsoft.AspNet.SignalR.Transports.TransportHeartbeat.CheckTimeoutAndKeepAlive(ConnectionMetadata metadata)
   at Microsoft.AspNet.SignalR.Transports.TransportHeartbeat.Beat(Object state)
[...]
   at System.Threading.TimerQueue.AppDomainTimerCallback()
```

**Comment by Praburaj** [comment]
I can't reproduce this any more. Closing down.
