### ISSUE TITLE
WebSocketException while shutting down iis express

### ISSUE THREAD

**Issue by Praburaj** [aspnet/SignalR-Server#86]
If i have an app with signalR on IIS express I see this exception on shutting down iis express sometimes. 

```
Request started: "GET" http://localhost:5001/signalr/negotiate?connectionData=%5B%7B%22name%22%3A%22announcement%22%7D%5D&clientProtocol=1.3&_=1426624395003
Request ended: http://localhost:5001/signalr/negotiate?connectionData=%5B%7B%22name%22%3A%22announcement%22%7D%5D&clientProtocol=1.3&_=1426624395003 with HTTP status 200.0
Request ended: http://localhost:5001/signalr/negotiate?connectionData=%5B%7B%22name%22%3A%22announcement%22%7D%5D&clientProtocol=1.3&_=1426624395003 with HTTP status 200.0
Request started: "GET" http://localhost:5001/signalr/connect?transport=webSockets&connectionToken=CfDJ8NAvQbz713hEsNZZ%2Byghhhz3agLoxSIZgnYbonSXTyMe7qqNFhqtqATXqJC%2BS4ybPKcdWGJGbCEN8TB84IcqzKdxKkufoJjpTEGWrtl%2F0jg%2BGLYxSUMV9cWnLGP%2FZiSVB9SJ64XKyxVl88xiJEHLe9wJTf8vkggSKh9A%2BmHXOfmm&connectionData=%5B%7B%22name%22%3A%22announcement%22%7D%5D&tid=7
Request ended: http://localhost:5001/signalr/connect?transport=webSockets&connectionToken=CfDJ8NAvQbz713hEsNZZ%2Byghhhz3agLoxSIZgnYbonSXTyMe7qqNFhqtqATXqJC%2BS4ybPKcdWGJGbCEN8TB84IcqzKdxKkufoJjpTEGWrtl%2F0jg%2BGLYxSUMV9cWnLGP%2FZiSVB9SJ64XKyxVl88xiJEHLe9wJTf8vkggSKh9A%2BmHXOfmm&connectionData=%5B%7B%22name%22%3A%22announcement%22%7D%5D&tid=7 with HTTP status 101.0
info    : [Microsoft.AspNet.SignalR.Transports.TransportHeartbeat] Connection 42a00397-1546-418c-b6ce-278d9bdab788 is New.
Request ended: http://localhost:5001/signalr/connect?transport=webSockets&connectionToken=CfDJ8NAvQbz713hEsNZZ%2Byghhhz3agLoxSIZgnYbonSXTyMe7qqNFhqtqATXqJC%2BS4ybPKcdWGJGbCEN8TB84IcqzKdxKkufoJjpTEGWrtl%2F0jg%2BGLYxSUMV9cWnLGP%2FZiSVB9SJ64XKyxVl88xiJEHLe9wJTf8vkggSKh9A%2BmHXOfmm&connectionData=%5B%7B%22name%22%3A%22announcement%22%7D%5D&tid=7 with HTTP status 101.0
Stopping IIS Express ...
error   : [Microsoft.AspNet.SignalR.Transports.WebSocketTransport] OnError(42a00397-1546-418c-b6ce-278d9bdab788, System.Net.WebSockets.WebSocketException (0x800703E3): The I/O operation has been aborted because of either a thread exit or an application request
   at Microsoft.AspNet.Loader.IIS.WebSockets.WebSocketPipe.<>c__DisplayClass9_0.<ReadFragmentAsync>b__0(Int32 hrError, UInt32 cbIO, Boolean fUtf8Encoded, Boolean fFinalFragment, Boolean fClose)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Loader.IIS.WebSockets.HeliosWebSocket.<DoWork>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Loader.IIS.WebSockets.HeliosWebSocket.<>c__DisplayClass36_0.<<ReceiveAsyncImpl>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketMessageReader.<ReadMessageAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__25.MoveNext())
info    : [Microsoft.AspNet.SignalR.Transports.WebSocketTransport] CompleteRequest (42a00397-1546-418c-b6ce-278d9bdab788)
info    : [Microsoft.AspNet.SignalR.Transports.WebSocketTransport] CloseSocket(42a00397-1546-418c-b6ce-278d9bdab788)

```

**Comment by moozzyk** [comment]
Related in 2.x: https://github.com/SignalR/SignalR/issues/3275

**Comment by muratg** [comment]
We'll refile if we see this again.
